title: 0  1 world
tagline: O ever youthful, O ever weeping.

author:
  name: r1mit
  url: https://twitter.com/r1mit1

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 3

tags_path: /tags/
categories_path: /categories/
